# Generated by Django 6.1 on 2026-08-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('imagem', models.FileField(upload_to='produtos/')),
                ('quantidade', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
