# Generated by Django 6.1 on 2026-09-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estoque_reservado',
            field=models.BooleanField(default=False),
        ),
    ]
